language: python
python:
  - "2.7"

before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis McTravis"
  - cp lib/python/mozilla_buildtools/test/hgrc ~/.hgrc
  - sudo apt-get install php5-cli

install:
  - pip install tox

script:
  - tox

after_script:
  - tox -e py27-coveralls

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# please comment out this section in your personal fork!
notifications:
  irc:
    channels:
      - "irc.mozilla.org#releng"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
